### ISSUE TITLE
Setup instructions

### ISSUE THREAD

**Issue by aindilis** [HaotianXue/Definition_Extraction#1]
This system looks very useful.  Can you please provide setup instructions for Linux?

**Comment by HaotianXue** [comment]
Hi aindilis,

All you need is a python 3.6+ environment with numpy, pytorch 1.4+(better with cuda), torchtext, scikit-learn and hugging-face's implementation for Bert: https://github.com/huggingface/transformers. Let me know if you have any other issues!

Haotian Xue & Zirong Chen

**Comment by aindilis** [comment]
Thank you so much!
